### ISSUE TITLE
No Variable for record-id in Recommendations

### ISSUE THREAD

**Issue by sascharolfsen** [FACT-Finder-Web-Components/shopware5-plugin#45]
https://github.com/FACT-Finder-Web-Components/shopware5-plugin/blob/450b5e8724d6e75f168b671ddf2211821ea61e43/Resources/views/frontend/factfinder/content/recommendation.tpl#L5

In the above line, the id is not set as variable. Must be `record-id="{$sArticle.mainVariantNumber}"`

**Comment by a-laurowski** [comment]
Hi @sascharolfsen  thanks for reporting that!
Fix is already merged to master branch
