### ISSUE TITLE
plugin.xml update

### ISSUE THREAD

**Issue by deubadario** [FACT-Finder-Web-Components/shopware5-plugin#70]
- FACT-Finder plugin version: 3.1.0

Please change in plugin.xml the version 3.0.2  to 3.1.0

![release v3 1 0](https://user-images.githubusercontent.com/106805244/176186265-9c9bea77-ea5e-4b97-8185-b3a307adfd16.PNG)

**Comment by a-laurowski** [comment]
hi @deubadario and thanks for letting us know. It will be fixed with the next release
